### ISSUE TITLE
data.json文件崩溃

### ISSUE THREAD

**Issue by 1812z** [wyf9/sleepy#3]
### 现象：网页打不开报内部服务器错误
File "/www/wwwroot/Mystatus/data.py", line 29, in load
self.data = json.load(file)
^^^^^^^^^^^^^^^
File "/www/server/pyporject_evn/Mystatus_venv/lib/python3.11/json/__init__.py", line 293, in load
return loads(fp.read(),
^^^^^^^^^
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 1118: invalid start byte
[pid: 3678088|app: 0|req: 84252/148738] 127.0.0.1 () {44 vars in 765 bytes} [Sat Dec 14 20:03:31 2024] GET / => generated 265 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 1)
### 情况: 
有人频繁刷新后,data.json文件直接打不开了，提示编码错误，实际上是源文件也炸了
### 建议：
可不可以把当前状态信息保存到变量，避免频繁IO读取？
以及状态码只临时保存到变量
读取json只在启动服务器加载一次？

**Comment by wyf9** [comment]
不过如果服务突然挂了（比如一些免费平台重启）状态会丢
我在想有没有更好的存储方案（就是不咋会sql）

**Comment by 1812z** [comment]
感觉都可以，都能避免大量读写
第一种就行了吧

但如果写入时候崩溃重启了，文件还可能损坏
建议把配置分开放？
 **config.json** 只读
**data.json** 定时读写

**Comment by wyf9** [comment]
可以
我看下现在的dev分支，确保可以运行后先改这个

**Comment by wyf9** [comment]
在改了在改了

对了 开发进度/todo会发在discord群组:
https://discord.gg/Vvex8Z6zKs

**Comment by wyf9** [comment]
√

**Comment by wyf9** [comment]
Preview: http://ddns.siiway.top:9010 (仅 Ipv6)
可以测试下

**Comment by 1812z** [comment]
OK,看样子是可以了:D
